version: '3.9'

services:

  service:
    build: .
    container_name: graduate_service
    environment:
      ### Server config ###
      # JVM
      JAVA_OPTS: "-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      MEMORY_OPTS: -Xms1g -Xmx1g
      # Postgres
      PG_DB_HOST: db
      PG_DB_PORT: 5432
      PG_DB_SCHEMA: graduate_schema_flyway
      PG_DB_USERNAME: graduate_user
      PG_DB_PASSWORD: graduate_password
    ports:
      - 8080:8080
      - 5005:5005 # java debug port
    depends_on:
      - db

  db:
    image: postgres
    container_name: graduate_db
    restart: always
    environment:
      POSTGRES_USER: graduate_user
      POSTGRES_PASSWORD: graduate_password
      POSTGRES_DB: graduate_schema_flyway
    ports:
      - 5432:5432
