# Default configuration properties
spring:
  datasource:
    url: jdbc:postgresql://${PG_DB_HOST}:${PG_DB_PORT}/${PG_DB_SCHEMA:}
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true

graduate:
  jwtSecret: ${JWT_SECRET}
  jwtAccessTokenExpirationMs: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}

---

# Configuration for the "local" profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/graduate_schema_flyway
    username: graduate_user
    password: graduate_password

graduate:
  jwtSecret: 576E5A7234753778214125432A462D4A614E645267556B58703273357638792F
  jwtAccessTokenExpirationMs: 7776000000 # 90 days
